name: Build Calculator to Java 18, 20, and 21

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [18, 20, 21]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            JAVA_VERSION=${{ matrix.java-version }}
          push: true
          tags: ghcr.io/${{ github.repository }}:java-${{ matrix.java-version }}
